STRUCT_BEGIN(lucid, FMaterialDescription, "")
    STRUCT_FIELD(UUID, Id, sole::INVALID_UUID, "Id of the material")	
    STRUCT_FIELD(FDString, Name, "", "Name of the material")	
    STRUCT_FIELD(FDString, ShaderName, "", "Name of the shader used by this material")	
STRUCT_END()

STRUCT_INHERIT_BEGIN(lucid, FFlatMaterialDescription, lucid::FMaterialDescription, "")
    STRUCT_STATIC_ARRAY(float, Color, 4, {0 COMMA 0 COMMA 0  COMMA 1}, "")	    
STRUCT_END()

STRUCT_INHERIT_BEGIN(lucid, FBlinnPhongMaterialDescription, lucid::FMaterialDescription, "")
    STRUCT_FIELD(int, Shininess, 32, "")	    
    STRUCT_STATIC_ARRAY(float, SpecularColor, 3, {0 COMMA 0 COMMA 0}, "")	    
    STRUCT_STATIC_ARRAY(float, DiffuseColor, 3, {0 COMMA 0 COMMA 0}, "")	    
STRUCT_END()

STRUCT_INHERIT_BEGIN(lucid, FBlinnPhongMapsMaterialDescription, lucid::FMaterialDescription, "")
    STRUCT_FIELD(int, Shininess, 32, "")	    
    STRUCT_FIELD(UUID, DiffuseTextureID, sole::INVALID_UUID, "")	    
    STRUCT_FIELD(UUID, SpecularTextureID, sole::INVALID_UUID, "")	    
    STRUCT_FIELD(UUID, NormalTextureID, sole::INVALID_UUID, "")
    STRUCT_FIELD(UUID, DisplacementTextureID, sole::INVALID_UUID, "")
    STRUCT_STATIC_ARRAY(float, SpecularColor, 3, {0 COMMA 0 COMMA 0}, "Fallback specular color when no specular map is present")	    
STRUCT_END()

STRUCT_BEGIN(lucid, FMaterialDatabaseEntry, "")
    STRUCT_FIELD(FDString, MaterialPath, "", "")
    STRUCT_FIELD(EFileFormat, FileFormat, lucid::EFileFormat::Json, "")
STRUCT_END()

STRUCT_BEGIN(lucid, FMaterialDatabase, "")
    STRUCT_DYNAMIC_ARRAY(FMaterialDatabaseEntry, FlatMaterials,  "")
    STRUCT_DYNAMIC_ARRAY(FMaterialDatabaseEntry, BlinnPhongMaterials,  "")
    STRUCT_DYNAMIC_ARRAY(FMaterialDatabaseEntry, BlinnPhongMapsMaterials,  "")
STRUCT_END()