ENUM_BEGIN(lucid::schema , ETextureResourceFormat, "Formats that the engine can import")
    ENUM_ITEM(UNKNOWN_TEXTURE_FORMAT, "")
    ENUM_ITEM(JPG_TEXTURE_FORMAT, "")
    ENUM_ITEM(PNG_TEXTURE_FORMAT, "")
ENUM_END()

ENUM_BEGIN(lucid::schema, ETextureResourceDataType, "Format in which texture data will be stored")
    ENUM_ITEM(UNSIGNED_BYTE, "")
    ENUM_ITEM(FLOAT, "")
ENUM_END()

STRUCT_BEGIN(lucid::schema, FTextureResource, "A texture asset that can be imported to the engine")
    STRUCT_FIELD(std::string, Name, "", "Name under which it'll be available in the engine")
    STRUCT_FIELD(lucid::schema::ETextureResourceFormat, Format, lucid::schema::ETextureResourceFormat::UNKNOWN_TEXTURE_FORMAT, "Format of the texture")
    STRUCT_FIELD(std::string, Path, "", "Path to the file, relative to the executable or absolute")
    STRUCT_FIELD(bool, GammaCorrect, false, "Wether to perform gamma correction when sending the texture to the GPU")
    STRUCT_FIELD(lucid::schema::ETextureResourceDataType, DataType, lucid::schema::ETextureResourceDataType::UNSIGNED_BYTE, "Format in which texture data will be stored")
    STRUCT_FIELD(i64, Offset, -1, "Offset at which the texture is location, -1 if the texture is stored in a standalone file")
    STRUCT_FIELD(i64, Size, -1, "Size of the texture in the file, -1 if the texture is stored in a standalone file")
STRUCT_END()